# Header
menu:
  Home: /
  Archives: /archives
  Github:
    url: https://github.com/gunar
    icon: github

# Title on top left of menu. Leave empty to use main blog title
# menu_title: Configurable Title

# URL of the Home page image
# index_cover: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg
index_cover: /img/background.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: gunar
  # Facebook comments
  # facebook:
  #   appid:
  #   comment_count: 5
  #   comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-52055630-3

# Addthis ID
# addthis:

# set your own favicon
# favicon:

# Social Accounts
twitter_url: https://twitter.com/gunar
twitter_handle: gunar
facebook_url:
github_url: https://github.com/gunar
gitlab_url:
linkedin_url: https://www.linkedin.com/in/gunargessner
mailto:
